language: r

sudo: required

before_install:
 - cd ./BAMMtools
 - echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile

warnings_are_errors: true

r_check_args: --as-cran --run-dontrun

r_binary_packages:
 - ape

after_script:
 - ./travis-tool.sh dump_logs
